[
	{
		"primary": "Programmimg",
		"secondary": "JS",
		"source": "api docs",
		"concept": "Objects",
		"effectiveness": "5 stars",
		"link": "www.ca.com",
		"date": "2016/10/18",
		"day": "Tuesday",
		"starttime": "8:00AM",
		"endtime": "8:30AM",
		"duration": 30
	},
	{
		"primary": "Programmimg",
		"secondary": "Mongo",
		"source": "In Class",
		"concept": "Database",
		"effectiveness": "5 stars",
		"link": "www.thinkful.com",
		"date": "2016/10/18",
		"day": "Tuesday",
		"starttime": "9:15AM",
		"endtime": "9:45AM",
		"duration": 30
	},
	{
		"_id": "",
		"primary": "Programmimg",
		"secondary": "Python",
		"source": "Think Python",
		"concept": "Classes",
		"effectiveness": "4 stars",
		"link": "python.com",
		"date": "2016/10/18",
		"day": "Tuesday",
		"starttime": "1:00PM",
		"endtime": "2:00PM",
		"duration": 60
	},
	{
		"primary": "Programmimg",
		"secondary": "HTML",
		"source": "Live Coding",
		"concept": "Practice",
		"effectiveness": "5 stars",
		"link": "na",
		"date": "2016/10/18",
		"day": "Tuesday",
		"starttime": "2:00PM",
		"endtime": "3:00PM",
		"duration": 60
	},
	{
		"_id": "",
		"primary": "Programmimg",
		"secondary": "CSS",
		"source": "Live Coding",
		"concept": "Bootstrap",
		"effectiveness": "5 stars",
		"link": "na",
		"date": "2016/10/17",
		"day": "Monday",
		"starttime": "11:00AM",
		"endtime": "11:15AM",
		"duration": 15
	},
	{
		"primary": "Programmimg",
		"secondary": "CSS",
		"source": "Live Coding",
		"concept": "Bootstrap",
		"effectiveness": "5 stars",
		"link": "na",
		"date": "2016/10/17",
		"day": "Monday",
		"starttime": "11:30AM",
		"endtime": "11:55AM",
		"duration": 25
	},
	{
		"_id": "",
		"primary": "Programmimg",
		"secondary": "JS",
		"source": "Code Academy",
		"concept": "Objects",
		"effectiveness": "1 stars",
		"link": "www.ca.com",
		"date": "2016/10/15",
		"day": "Saturday",
		"starttime": "8:00AM",
		"endtime": "8:45AM",
		"duration": 45
	},
	{
		"primary": "Programmimg",
		"secondary": "JS",
		"source": "Tree House",
		"concept": "Objects",
		"effectiveness": "5 stars",
		"link": "treehouse.com",
		"date": "2016/10/14",
		"day": "Friday",
		"starttime": "11:00AM",
		"endtime": "11:15AM",
		"duration": 15
	},
	{
		"_id": "",
		"primary": "Programmimg",
		"secondary": "JS",
		"source": "In Class",
		"concept": "Node",
		"effectiveness": "2 stars",
		"link": "www.thinkful.com",
		"date": "2016/10/13",
		"day": "Thursday",
		"starttime": "2:00PM",
		"endtime": "2:30PM",
		"duration": 30
	},
	{
		"primary": "Programmimg",
		"secondary": "JS",
		"source": "In Class",
		"concept": "Node",
		"effectiveness": "5 stars",
		"link": "www.thinkful.com",
		"date": "2016/10/13",
		"day": "Thursday",
		"starttime": "3:00PM",
		"endtime": "3:15PM",
		"duration": 15
	},
	{
		"primary": "Programmimg",
		"secondary": "React",
		"source": "In Class",
		"concept": "Node",
		"effectiveness": "5 stars",
		"link": "www.thinkful.com",
		"date": "2016/10/13",
		"day": "Thursday",
		"starttime": "5:00PM",
		"endtime": "5:15PM",
		"duration": 15
	},
	{
		"primary": "Computer Science",
		"secondary": "Algorithims",
		"source": "Tree House",
		"concept": "Big O",
		"effectiveness": "4 stars",
		"link": "treehouse.com",
		"date": "2016/10/13",
		"day": "Thursday",
		"starttime": "9:15AM",
		"endtime": "9:30AM",
		"duration": 15
	},
	{
		"primary": "Computer Science",
		"secondary": "Algorithims",
		"source": "Tree House",
		"concept": "Big O",
		"effectiveness": "2 stars",
		"link": "treehouse.com",
		"date": "2016/10/12",
		"day": "Wednesday",
		"starttime": "8:00AM",
		"endtime": "8:30AM",
		"duration": 30
	},
	{
		"primary": "Computer Science",
		"secondary": "Algorithims",
		"source": "Tree House",
		"concept": "Big O",
		"effectiveness": "2 stars",
		"link": "treehouse.com",
		"date": "2016/10/12",
		"day": "Wednesday",
		"starttime": "8:35AM",
		"endtime": "9:00AM",
		"duration": 25
	},
	{
		"primary": "Computer Science",
		"secondary": "Data Sets",
		"source": "In Class",
		"concept": "Linked Lists",
		"effectiveness": "3 stars",
		"link": "www.thinkful.com",
		"date": "2016/10/12",
		"day": "Wednesday",
		"starttime": "9:00AM",
		"endtime": "9:00AM",
		"duration": 60
	},
	{
		"primary": "Computer Science",
		"secondary": "Data Sets",
		"source": "In Class",
		"concept": "Trees",
		"effectiveness": "1 star",
		"link": "www.thinkful.com",
		"date": "2016/10/10",
		"day": "Mondonday",
		"starttime": "10:00AM",
		"endtime": "11:55AM",
		"duration": 115
	}
]